### ISSUE TITLE
Biopython is a dependency but is not listed in packages.txt

### ISSUE THREAD

**Issue by oneillkza** [laurentijntilleman/CoLoRGen#2]
When installing clean (in a Docker container), various errors like this occur:

```
Traceback (most recent call last):
  File "/opt/CoLoRGen/variant_caller.py", line 4, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
```

It looks like the `bio` package needs to be added to packages.txt

**Comment by laurentijntilleman** [comment]
I have added the bio python package to the packages.txt file
